apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
spec:
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      serviceAccountName: default
      containers:
      - name: server
        image: csecsecse/quote-service
        ports:
        - containerPort: 50055
        env:
        - name: PORT
          value: "50055"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  type: ClusterIP
  selector:
    app: quote-service
  ports:
  - name: grpc
    port: 50055
    targetPort: 50055